### ISSUE TITLE
Compile error:  undefined: metricdata.LabelKey

### ISSUE THREAD

**Issue by bzon** [census-ecosystem/opencensus-go-exporter-stackdriver#145]
Please answer these questions before submitting a bug report.

### What version of the Exporter are you using?

Stackdriver 0.11.0

### What version of OpenCensus are you using?

```toml
[[constraint]]
 name = "go.opencensus.io"
 version = "0.20.2"
```

### What version of Go are you using?

```txt
go version go1.12.4 darwin/amd64
```

### What did you do?
If possible, provide a recipe for reproducing the error.

```bash
dep ensure -add "contrib.go.opencensus.io/exporter/stackdriver"
```

Write the code.

```golang
sd, err := stackdriver.NewExporter(stackdriver.Options{
	ProjectID: "project-id",
})
if err != nil {
		panic(err)
}

defer sd.Flush()
trace.RegisterExporter(sd)
```

### What did you expect to see?

No error.

### What did you see instead?

```
vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics.go:165:73: undefined: metricdata.LabelKey
vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics.go:249:74: undefined: metricdata.LabelKey
```

### Additional context

The workaround is to use a previous version and this is what I use that still compiles fine.

```toml
[[projects]]
  digest = "1:caafa98969edd6d051deba6667ac0b98b32e5da133c4253ac7657fb2c052fa5e"
  name = "contrib.go.opencensus.io/exporter/stackdriver"
  packages = [
    ".",
    "monitoredresource",
  ]
  pruneopts = "UT"
  revision = "ab5a58af316a529613aadf9f50eeed1b6f044b2f"
  version = "v0.9.2"
```

**Comment by songy23** [comment]
This is a known breaking change added in https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/136. Please try upgrading `go.opencensus.io` to v0.21.0 and this should be resolved.

**Comment by songy23** [comment]
Closing, please feel free to reopen if the problem persists after upgrading the version of opencensus core library.
